spring:
  profiles:
    active: secret
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

# OpenVidu 설정
openvidu:
  url: https://k11e204.p.ssafy.io:8443
  secret: MY_SECRET

server:
  port: 8081

