INSERT INTO family (created_at, username, password)
SELECT
  NOW() - INTERVAL (RAND()*365) DAY,
  CONCAT('test_user_', n),
  '1234'
FROM (
  SELECT @row := @row + 1 AS n
  FROM (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
        UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
        UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19) a,
       (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
       (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
       (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d,
       (SELECT @row := 0) r
) t;

INSERT INTO member (shell, created_at, img, name, family_id)
SELECT
    100000,
    NOW() - INTERVAL (RAND() * 365) DAY,
    NULL,
    CONCAT('child_', 1, '_', t.n),
    1
FROM (
    SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
    UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
    UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
    UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
    UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25
    UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
    UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35
    UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40
    UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45
    UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL SELECT 50
    UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55
    UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60
    UNION ALL SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL SELECT 64 UNION ALL SELECT 65
    UNION ALL SELECT 66 UNION ALL SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL SELECT 70
    ) t;

INSERT INTO member (shell, created_at, img, name, family_id)
SELECT
  0,NOW() - INTERVAL (RAND() * 365) DAY,   -- 최근 1년 내 랜덤 날짜
  NULL,                                  -- img 비워두기
  CONCAT('child_', f.id, '_', s.n),      -- 이름: child_가족ID_1 또는 _2
  f.id                                   -- family_id
FROM family f
JOIN (
  SELECT 1 AS n
  UNION ALL
  SELECT 2
) s;

-- 전체 건수(40,000 기대)
SELECT COUNT(*) AS member_cnt FROM member;

-- 가족별 2명인지 검증
SELECT family_id, COUNT(*) AS cnt
FROM member
GROUP BY family_id
HAVING cnt <> 2
LIMIT 10;

INSERT INTO sticker (img, price)
SELECT
  CONCAT('/img/sticker/', n, '.png') AS img,
  FLOOR(100 + (RAND() * 4900))       AS price  -- 100~5000 랜덤 가격
FROM (
  SELECT @row := @row + 1 AS n
  FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
       (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
       (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
       (SELECT @row := 0) r
) t
WHERE n <= 300;

INSERT INTO earned_sticker (created_at, member_id, sticker_id)
SELECT
  NOW() - INTERVAL (RAND() * 120) DAY,             -- 최근 4개월 내 랜덤 획득일
  m.id AS member_id,
  ((m.id + s.n) % 300) + 1 AS sticker_id           -- 1~300 순환
FROM member m
JOIN (
  SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3  -- 각 멤버당 3개
) s;

-- coupon 300,000개: 가족당 15개씩 생성 (간단/빠름)
INSERT INTO coupon (created_at, description, price, purchased_at, family_id)
SELECT
  NOW() - INTERVAL FLOOR(RAND()*365) DAY,            -- 최근 1년 랜덤 생성일
  CONCAT('coupon_', f.id, '_', s.n),                 -- 예: coupon_123_7
  FLOOR(500 + RAND()*9501),                          -- 500 ~ 10,000
  NULL,                                              -- 아직 미구매
  f.id
FROM family f
JOIN (
  SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
  UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
) s;

DROP TEMPORARY TABLE IF EXISTS tmp_coupons;
CREATE TEMPORARY TABLE tmp_coupons (
  coupon_id BIGINT PRIMARY KEY
) ENGINE=Memory;

INSERT INTO tmp_coupons (coupon_id)
SELECT c.id
FROM coupon c
LEFT JOIN earned_coupon ec ON ec.coupon_id = c.id
WHERE c.purchased_at IS NULL
  AND ec.coupon_id IS NULL
LIMIT 100000;

INSERT INTO earned_coupon (coupon_id, member_id, used_at)
SELECT 
  t.coupon_id,
  (
    SELECT m.id
    FROM member m
    WHERE m.family_id = c.family_id
    ORDER BY RAND()          -- 간단히 랜덤 배정(아주 큰 데이터면 느릴 수 있음)
    LIMIT 1
  ) AS member_id,
  NULL
FROM tmp_coupons t
JOIN coupon c ON c.id = t.coupon_id;

UPDATE coupon c
JOIN tmp_coupons t ON t.coupon_id = c.id
SET c.purchased_at = NOW(6);

-- 무작위 30,000건 픽 → 사용 처리(used_at은 purchased_at~지금 사이 임의 시각)
WITH picked AS (
  SELECT e.id, c.purchased_at
  FROM earned_coupon e
  JOIN coupon c ON c.id = e.coupon_id
  WHERE e.used_at IS NULL
  ORDER BY RAND()
  LIMIT 30000
)
UPDATE earned_coupon e
JOIN picked p ON p.id = e.id
SET e.used_at = TIMESTAMPADD(
  SECOND,
  FLOOR(RAND() * GREATEST(1, TIMESTAMPDIFF(SECOND, p.purchased_at, NOW(6)))),
  p.purchased_at
);

INSERT INTO shell (member_id, stock, content, last_updated)
SELECT n, 100000, 'MISSION', NOW()
FROM (
  SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
  UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
  UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
  UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25
  UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
  UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35
  UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40
  UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45
  UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL SELECT 50
  UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55
  UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60
  UNION ALL SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL SELECT 64 UNION ALL SELECT 65
  UNION ALL SELECT 66 UNION ALL SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL SELECT 70
) t;

UPDATE member
SET shell = 100000
WHERE id = 1;

SET GLOBAL slow_query_log = ON;
SET GLOBAL long_query_time = 0.1;
