FROM gradle:8.7-jdk17 AS build
WORKDIR /src
COPY . .
RUN gradle clean bootJar -x test

# 2) Run stage
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /src/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-XX:+UseG1GC","-Xms512m","-Xmx2048m","-jar","/app/app.jar"]